# Based on https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  UseCache: true
  DisplayCopNames: true
  MaxFilesInCache: 3000

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/custom.yml
  - .rubocop/strict.yml